---
# TODO(arxcruz): Remove this once libvirt 10 is available on centos stream
- name: Add master repository containing libvirt 10
  shell:
    cmd: |
      dnf config-manager --add-repo https://trunk.rdoproject.org/centos9-master/delorean-deps-test.repo && dnf update -y
  become: true

- name: Install libvirt packages
  tags:
    - install
    - libvirt
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ edpm_libvirt_packages }}"
  notify:
    - Restart libvirt

- name: Ensure monolithic libvirt is not enabled or running
  tags:
    - install
    - libvirt
  become: true
  ansible.builtin.systemd:
    name: "libvirtd"
    enabled: false
    masked: true
    state: stopped

- name: Ensure libvirt services are enabled and running
  tags:
    - install
    - libvirt
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    enabled: true
    masked: false
  loop: "{{ edpm_libvirt_services }}"

- name: Configure socket activation for libvirt services
  tags:
    - install
    - libvirt
  become: true
  vars:
    socket_suffix: ".socket"
    socket_types: ['', '-ro', '-admin']
  ansible.builtin.systemd:
    name: "{{ item.0 }}{{ item.1 }}{{ socket_suffix }}"
    enabled: true
    masked: false
  when: not (item.0 == 'virtlogd' and item.1 == '-ro')
  loop: "{{ edpm_libvirt_services | product(socket_types) | list }}"
